const refinery = extend( GenericCrafter, "refinery", {});
refinery.drawer = new DrawRotator();
const bigKiln = extend( AttributeCrafter, "meta-kilnii", {});
bigKiln.drawer = new DrawSmelter();
const smolSteel = extend( GenericCrafter, "steel-smelter", {});
smolSteel.drawer = new DrawSmelter();
const bigSteel = extend( AttributeCrafter, "steel-forge", {});
bigSteel.drawer = new DrawSmelter();
const silicglass = extend( GenericCrafter, "silic-glass-smelter", {});
const pain = new DrawSmelter();
pain.flameRadius = 2
silicglass.drawer = pain
const quartRefine = extend( GenericCrafter, "quartz-refinery", {});
const spritePain = new DrawSmelter
spritePain.spinSpeed = 5
quartRefine.drawer = spritePain
