const refinery = extend( GenericCrafter, "refinery", {});
refinery.drawer = new DrawRotator();
const bigKiln = extend( AttributeCrafter, "meta-kilnii", {});
bigKiln.drawer = new DrawSmelter();
const smolSteel = extend( GenericCrafter, "steel-smelter", {});
smolSteel.drawer = new DrawSmelter();
const bigSteel = extend( AttributeCrafter, "steel-forge", {});
bigSteel.drawer = new DrawSmelter();
const silicglass = extend( GenericCrafter, "silic-glass-smelter", {});
const pain = new DrawSmelter();
pain.flameRadius = 2
pain.lightRadius = 0
pain.lightAlpha = 0.15
silicglass.drawer = pain
const quartRefine = extend( GenericCrafter, "quartz-refinery", {});
const spri = new DrawRotator();
spri.spinSpeed = 5
quartRefine.drawer = spri
const thiccSilicGlass = extend( GenericCrafter, "silic-glass-forge", {});
thiccSilicGlass.drawer = pain
